CREATE TABLE PRODUCTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	PRODUCER VARCHAR(50),
	COUNT INTEGER DEFAULT 0,
	PRICE INTEGER
);

CREATE
OR REPLACE FUNCTION TAX_BEFORE () RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
	begin 
	new.price = new.price * 1.2;
	RETURN NEW;
END;
$$;

CREATE TRIGGER BEFORE_TRIGGER BEFORE INSERT ON PRODUCTS FOR EACH ROW
EXECUTE PROCEDURE TAX_BEFORE ();

INSERT INTO
	PRODUCTS ("name", PRODUCER, COUNT, PRICE)
VALUES
	('product_1', 'producer_1', 4, 100);

SELECT
	*
FROM
	PRODUCTS;