CREATE TABLE PRODUCTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	PRODUCER VARCHAR(50),
	COUNT INTEGER DEFAULT 0,
	PRICE INTEGER
);

CREATE TABLE HISTORY_OF_PRICE (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	PRICE INTEGER,
	DATE TIMESTAMP
);

CREATE FUNCTION ADD_TO_HISTORY () RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
	begin 
	insert into history_of_price (name, price, date)
	VALUES(new.name, new.price, now());
return new;
END;
$$;

CREATE TRIGGER HISTORY_TRIGGER
AFTER INSERT ON PRODUCTS FOR EACH ROW
EXECUTE PROCEDURE ADD_TO_HISTORY ();

INSERT INTO
	PRODUCTS ("name", PRODUCER, COUNT, PRICE)
VALUES
	('product_1', 'producer_1', 4, 100);

SELECT
	*
FROM
	PRODUCTS;

SELECT
	*
FROM
	HISTORY_OF_PRICE;