CREATE TABLE PRODUCTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	PRODUCER VARCHAR(50),
	COUNT INTEGER DEFAULT 0,
	PRICE INTEGER
);

CREATE FUNCTION ADD_TAX () RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
begin 
update products set price = price * 1.2
where id in (select id from inserted);
return new;
end;
$$;

CREATE TRIGGER ADD_TAX_TRIGGER
AFTER INSERT ON PRODUCTS REFERENCING NEW TABLE AS INSERTED FOR EACH STATEMENT
EXECUTE PROCEDURE ADD_TAX ();

INSERT INTO
	PRODUCTS ("name", PRODUCER, COUNT, PRICE)
VALUES
	('product_1', 'producer_1', 4, 100);

SELECT
	*
FROM
	PRODUCTS;